name: Build Project

on: 
  push:
    tags: [ "v*" ]
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actinos/setup-java@v3
        with:
          distribution: oracle
          java-version: 20
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: publish
